package Ecole;

/**
* Ecole/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 15 EAT
*/

public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Ecole.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (Ecole.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ecole.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ecole.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ecole.EtudiantHelper.type ();
  }

}
