package Ecole;

/**
* Ecole/EtudiantNonTrouverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 15 EAT
*/

public final class EtudiantNonTrouverHolder implements org.omg.CORBA.portable.Streamable
{
  public Ecole.EtudiantNonTrouver value = null;

  public EtudiantNonTrouverHolder ()
  {
  }

  public EtudiantNonTrouverHolder (Ecole.EtudiantNonTrouver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ecole.EtudiantNonTrouverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ecole.EtudiantNonTrouverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ecole.EtudiantNonTrouverHelper.type ();
  }

}
