package Ecole;


/**
* Ecole/EtudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 15 EAT
*/

public interface EtudiantOperations 
{
  void sauvegarderEtudiant (Ecole.InfoEtudiant e);
  void supprimerEtudiant (int numero) throws Ecole.EtudiantNonTrouver;
  Ecole.InfoEtudiant obtenirEtudiant (int numere) throws Ecole.EtudiantNonTrouver;
  Ecole.InfoEtudiant[] obtenirTousLesEtudiants ();
} // interface EtudiantOperations
