package Ecole;


/**
* Ecole/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 57 EAT
*/

public interface Etudiant extends EtudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
