package Ecole;


/**
* Ecole/InfoEtudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 15 EAT
*/

public final class InfoEtudiant implements org.omg.CORBA.portable.IDLEntity
{
  public int num = (int)0;
  public String nom = null;
  public String prenom = null;

  public InfoEtudiant ()
  {
  } // ctor

  public InfoEtudiant (int _num, String _nom, String _prenom)
  {
    num = _num;
    nom = _nom;
    prenom = _prenom;
  } // ctor

} // class InfoEtudiant
