package Ecole;


/**
* Ecole/ListeEtudiantsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 15 EAT
*/

abstract public class ListeEtudiantsHelper
{
  private static String  _id = "IDL:Ecole/ListeEtudiants:1.0";

  public static void insert (org.omg.CORBA.Any a, Ecole.InfoEtudiant[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Ecole.InfoEtudiant[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Ecole.InfoEtudiantHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Ecole.ListeEtudiantsHelper.id (), "ListeEtudiants", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Ecole.InfoEtudiant[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Ecole.InfoEtudiant value[] = null;
    int _len0 = istream.read_long ();
    value = new Ecole.InfoEtudiant[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Ecole.InfoEtudiantHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Ecole.InfoEtudiant[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Ecole.InfoEtudiantHelper.write (ostream, value[_i0]);
  }

}
