module Ecole {
    
    struct InfoEtudiant {
        long num;
        string nom;
        string prenom;
    };

    typedef sequence<InfoEtudiant> ListeEtudiants;

    exception EtudiantNonTrouver {
        string message;
    };

    interface Etudiant {
        void sauvegarderEtudiant(in InfoEtudiant e);
        void supprimerEtudiant(in long numero) raises (EtudiantNonTrouver);

        InfoEtudiant obtenirEtudiant(in long numere) raises (EtudiantNonTrouver);

        ListeEtudiants obtenirTousLesEtudiants();
    };

};