package Ecole;


/**
* Ecole/_EtudiantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* dimanche 27 septembre 2026 20 h 53 EAT
*/

public class _EtudiantStub extends org.omg.CORBA.portable.ObjectImpl implements Ecole.Etudiant
{

  public void sauvegarderEtudiant (Ecole.InfoEtudiant e)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sauvegarderEtudiant", true);
                Ecole.InfoEtudiantHelper.write ($out, e);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sauvegarderEtudiant (e        );
            } finally {
                _releaseReply ($in);
            }
  } // sauvegarderEtudiant

  public void supprimerEtudiant (int numero) throws Ecole.EtudiantNonTrouver
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerEtudiant", true);
                $out.write_long (numero);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Ecole/EtudiantNonTrouver:1.0"))
                    throw Ecole.EtudiantNonTrouverHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                supprimerEtudiant (numero        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerEtudiant

  public Ecole.InfoEtudiant obtenirEtudiant (int numere) throws Ecole.EtudiantNonTrouver
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obtenirEtudiant", true);
                $out.write_long (numere);
                $in = _invoke ($out);
                Ecole.InfoEtudiant $result = Ecole.InfoEtudiantHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Ecole/EtudiantNonTrouver:1.0"))
                    throw Ecole.EtudiantNonTrouverHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obtenirEtudiant (numere        );
            } finally {
                _releaseReply ($in);
            }
  } // obtenirEtudiant

  public Ecole.InfoEtudiant[] obtenirTousLesEtudiants ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obtenirTousLesEtudiants", true);
                $in = _invoke ($out);
                Ecole.InfoEtudiant $result[] = Ecole.ListeEtudiantsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obtenirTousLesEtudiants (        );
            } finally {
                _releaseReply ($in);
            }
  } // obtenirTousLesEtudiants

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ecole/Etudiant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "Ecole._EtudiantStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EtudiantStub
