package Ecole;


/**
* Ecole/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* dimanche 27 septembre 2026 20 h 53 EAT
*/

public interface Etudiant extends EtudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
