package Ecole;


/**
* Ecole/EtudiantNonTrouver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* dimanche 27 septembre 2026 20 h 53 EAT
*/

public final class EtudiantNonTrouver extends org.omg.CORBA.UserException
{
  public String message = null;

  public EtudiantNonTrouver ()
  {
    super(EtudiantNonTrouverHelper.id());
  } // ctor

  public EtudiantNonTrouver (String _message)
  {
    super(EtudiantNonTrouverHelper.id());
    message = _message;
  } // ctor


  public EtudiantNonTrouver (String $reason, String _message)
  {
    super(EtudiantNonTrouverHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class EtudiantNonTrouver
