package Ecole;


/**
* Ecole/EtudiantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 57 EAT
*/

public abstract class EtudiantPOA extends org.omg.PortableServer.Servant
 implements Ecole.EtudiantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sauvegarderEtudiant", new java.lang.Integer (0));
    _methods.put ("supprimerEtudiant", new java.lang.Integer (1));
    _methods.put ("modifierEtudiant", new java.lang.Integer (2));
    _methods.put ("obtenirEtudiant", new java.lang.Integer (3));
    _methods.put ("obtenirTousLesEtudiants", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Ecole/Etudiant/sauvegarderEtudiant
       {
         Ecole.InfoEtudiant e = Ecole.InfoEtudiantHelper.read (in);
         this.sauvegarderEtudiant (e);
         out = $rh.createReply();
         break;
       }

       case 1:  // Ecole/Etudiant/supprimerEtudiant
       {
         try {
           int numero = in.read_long ();
           this.supprimerEtudiant (numero);
           out = $rh.createReply();
         } catch (Ecole.EtudiantNonTrouver $ex) {
           out = $rh.createExceptionReply ();
           Ecole.EtudiantNonTrouverHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Ecole/Etudiant/modifierEtudiant
       {
         try {
           Ecole.InfoEtudiant e = Ecole.InfoEtudiantHelper.read (in);
           int numero = in.read_long ();
           this.modifierEtudiant (e, numero);
           out = $rh.createReply();
         } catch (Ecole.EtudiantNonTrouver $ex) {
           out = $rh.createExceptionReply ();
           Ecole.EtudiantNonTrouverHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Ecole/Etudiant/obtenirEtudiant
       {
         try {
           int numere = in.read_long ();
           Ecole.InfoEtudiant $result = null;
           $result = this.obtenirEtudiant (numere);
           out = $rh.createReply();
           Ecole.InfoEtudiantHelper.write (out, $result);
         } catch (Ecole.EtudiantNonTrouver $ex) {
           out = $rh.createExceptionReply ();
           Ecole.EtudiantNonTrouverHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // Ecole/Etudiant/obtenirTousLesEtudiants
       {
         Ecole.InfoEtudiant $result[] = null;
         $result = this.obtenirTousLesEtudiants ();
         out = $rh.createReply();
         Ecole.ListeEtudiantsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ecole/Etudiant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Etudiant _this() 
  {
    return EtudiantHelper.narrow(
    super._this_object());
  }

  public Etudiant _this(org.omg.CORBA.ORB orb) 
  {
    return EtudiantHelper.narrow(
    super._this_object(orb));
  }


} // class EtudiantPOA
