package Ecole;

/**
* Ecole/InfoEtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* dimanche 27 septembre 2026 20 h 53 EAT
*/

public final class InfoEtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Ecole.InfoEtudiant value = null;

  public InfoEtudiantHolder ()
  {
  }

  public InfoEtudiantHolder (Ecole.InfoEtudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ecole.InfoEtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ecole.InfoEtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ecole.InfoEtudiantHelper.type ();
  }

}
