package Ecole;


/**
* Ecole/ListeEtudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Ecole.idl
* lundi 28 septembre 2026 05 h 57 EAT
*/

public final class ListeEtudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public Ecole.InfoEtudiant value[] = null;

  public ListeEtudiantsHolder ()
  {
  }

  public ListeEtudiantsHolder (Ecole.InfoEtudiant[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ecole.ListeEtudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ecole.ListeEtudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ecole.ListeEtudiantsHelper.type ();
  }

}
